In [102]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Utility

In [103]:
personU = pd.read_csv('person_utility.csv')
bankU = pd.read_csv('bank_utility.csv')

bankU = bankU.drop('Unnamed: 0', axis=1, errors='ignore')
personU = personU.drop('Unnamed: 0', axis=1, errors='ignore')

In [104]:
bankU

,1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,30
0,1.01,1.0201,1.0303,1.0406,1.0510,1.0615,1.0721,1.0829,1.0937,1.1046,...,1.2324,1.2447,1.2572,1.2697,1.2824,1.2953,1.3082,1.3213,1.3345,1.3478
1,1.02,1.0404,1.0612,1.0824,1.1041,1.1262,1.1487,1.1717,1.1951,1.2190,...,1.5157,1.5460,1.5769,1.6084,1.6406,1.6734,1.7069,1.7410,1.7758,1.8114
2,1.03,1.0609,1.0927,1.1255,1.1593,1.1941,1.2299,1.2668,1.3048,1.3439,...,1.8603,1.9161,1.9736,2.0328,2.0938,2.1566,2.2213,2.2879,2.3566,2.4273
3,1.04,1.0816,1.1249,1.1699,1.2167,1.2653,1.3159,1.3686,1.4233,1.4802,...,2.2788,2.3699,2.4647,2.5633,2.6658,2.7725,2.8834,2.9987,3.1187,3.2434
4,1.05,1.1025,1.1576,1.2155,1.2763,1.3401,1.4071,1.4775,1.5513,1.6289,...,2.7860,2.9253,3.0715,3.2251,3.3864,3.5557,3.7335,3.9201,4.1161,4.3219
5,1.06,1.1236,1.1910,1.2625,1.3382,1.4185,1.5036,1.5938,1.6895,1.7908,...,3.3996,3.6035,3.8197,4.0489,4.2919,4.5494,4.8223,5.1117,5.4184,5.7435
6,1.07,1.1449,1.2250,1.3108,1.4026,1.5007,1.6058,1.7182,1.8385,1.9672,...,4.1406,4.4304,4.7405,5.0724,5.4274,5.8074,6.2139,6.6488,7.1143,7.6123
7,1.08,1.1664,1.2597,1.3605,1.4693,1.5869,1.7138,1.8509,1.9990,2.1589,...,5.0338,5.4365,5.8715,6.3412,6.8485,7.3964,7.9881,8.6271,9.3173,10.0627
8,1.09,1.1881,1.2950,1.4116,1.5386,1.6771,1.8280,1.9926,2.1719,2.3674,...,6.1088,6.6586,7.2579,7.9111,8.6231,9.3992,10.2451,11.1671,12.1722,13.2677
9,1.10,1.2100,1.3310,1.4641,1.6105,1.7716,1.9487,2.1436,2.3579,2.5937,...,7.4002,8.1403,8.9543,9.8497,10.8347,11.9182,13.1100,14.4210,15.8631,17.4494

In [105]:
personU

,1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,30
0,0.9901,0.9803,0.9706,0.9610,0.9515,0.9420,0.9327,0.9235,0.9143,0.9053,...,0.8114,0.8034,0.7954,0.7876,0.7798,0.7720,0.7644,0.7568,0.7493,0.7419
1,0.9804,0.9612,0.9423,0.9238,0.9057,0.8880,0.8706,0.8535,0.8368,0.8203,...,0.6598,0.6468,0.6342,0.6217,0.6095,0.5976,0.5859,0.5744,0.5631,0.5521
2,0.9709,0.9426,0.9151,0.8885,0.8626,0.8375,0.8131,0.7894,0.7664,0.7441,...,0.5375,0.5219,0.5067,0.4919,0.4776,0.4637,0.4502,0.4371,0.4243,0.4120
3,0.9615,0.9246,0.8890,0.8548,0.8219,0.7903,0.7599,0.7307,0.7026,0.6756,...,0.4388,0.4220,0.4057,0.3901,0.3751,0.3607,0.3468,0.3335,0.3207,0.3083
4,0.9524,0.9070,0.8638,0.8227,0.7835,0.7462,0.7107,0.6768,0.6446,0.6139,...,0.3589,0.3418,0.3256,0.3101,0.2953,0.2812,0.2678,0.2551,0.2429,0.2314
5,0.9434,0.8900,0.8396,0.7921,0.7473,0.7050,0.6651,0.6274,0.5919,0.5584,...,0.2942,0.2775,0.2618,0.2470,0.2330,0.2198,0.2074,0.1956,0.1846,0.1741
6,0.9346,0.8734,0.8163,0.7629,0.7130,0.6663,0.6227,0.5820,0.5439,0.5083,...,0.2415,0.2257,0.2109,0.1971,0.1842,0.1722,0.1609,0.1504,0.1406,0.1314
7,0.9259,0.8573,0.7938,0.7350,0.6806,0.6302,0.5835,0.5403,0.5002,0.4632,...,0.1987,0.1839,0.1703,0.1577,0.1460,0.1352,0.1252,0.1159,0.1073,0.0994
8,0.9174,0.8417,0.7722,0.7084,0.6499,0.5963,0.5470,0.5019,0.4604,0.4224,...,0.1637,0.1502,0.1378,0.1264,0.1160,0.1064,0.0976,0.0895,0.0822,0.0754
9,0.9091,0.8264,0.7513,0.6830,0.6209,0.5645,0.5132,0.4665,0.4241,0.3855,...,0.1351,0.1228,0.1117,0.1015,0.0923,0.0839,0.0763,0.0693,0.0630,0.0573

## probability

In [106]:
prob = pd.read_csv('prob.csv')
prob = prob['Probability']
prob = prob.values.reshape(-1, 1)
prob

array([[0.217391],
       [0.312253],
       [0.256917],
       [0.067194],
       [0.047431],
       [0.063241],
       [0.023715],
       [0.011858],
       [0.      ],
       [0.      ]])

## Decsion matrix

In [107]:
result_matrix_person = np.matmul(personU.transpose() , prob)

In [108]:
result_matrix_person

           0
1   0.973398
2   0.947726
3   0.922915
4   0.899003
5   0.875900
6   0.853587
7   0.832025
8   0.811165
9   0.791002
10  0.771492
11  0.752640
12  0.734374
13  0.716712
14  0.699602
15  0.683007
16  0.666935
17  0.651403
18  0.636303
19  0.621649
20  0.607487
21  0.593705
22  0.580352
23  0.567405
24  0.554808
25  0.542589
26  0.530722
27  0.519208
28  0.507998
29  0.497082
30  0.486524

In [109]:
result_matrix_bank = np.matmul(bankU.transpose() , prob)

In [110]:
result_matrix_bank

           0
1   1.027589
2   1.056202
3   1.085875
4   1.116683
5   1.148686
6   1.181901
7   1.216386
8   1.252272
9   1.289526
10  1.328263
11  1.368606
12  1.410552
13  1.454231
14  1.499750
15  1.547152
16  1.596533
17  1.647985
18  1.701673
19  1.757729
20  1.816193
21  1.877281
22  1.941023
23  2.007651
24  2.077260
25  2.150088
26  2.226261
27  2.305949
28  2.389346
29  2.476712
30  2.568232

## Expected values

In [111]:
def expected_value(values, probs):
    values = np.asarray(values)
    weights = np.asarray(probs)
    return (values * probs).sum() / probs.sum()

In [112]:
print (expected_value(bankU, prob))

49.5235892376

In [113]:
print (expected_value(personU, prob))

20.828720440500003

The value you calculated, 20, represents the expected value (or expected utility) of the utility matrix given the corresponding probability matrix. In the context of utility theory or decision theory, the expected value is a measure that represents the average utility of a set of outcomes, weighted by their probabilities.

In your case:

    The utility matrix (values) represents the utility associated with each possible outcome or state.
    The probability matrix (probs) represents the likelihood or probability of each corresponding outcome or state.

The expected value is calculated by multiplying each utility value by its probability, summing up these products, and then dividing by the sum of probabilities.

Here's the calculation in your case:

E[U]=utility value1Ã—probability1+utility value2Ã—probability2+â€¦+utility valuenÃ—probabilitynprobability1+probability2+â€¦+probabilitynE[U]=probability1â€‹+probability2â€‹+â€¦+probabilitynâ€‹utility value1â€‹Ã—probability1â€‹+utility value2â€‹Ã—probability2â€‹+â€¦+utility valuenâ€‹Ã—probabilitynâ€‹â€‹

Given that you obtained 20, it suggests that, on average, the expected utility of the outcomes, taking into account their probabilities, is 20. This can be interpreted as the average "value" or "satisfaction" you might expect to receive from the set of possible outcomes, considering their respective likelihoods.

## Kalkulere beste lÃ¸sning

In [137]:
def find_loan_term(utility_matrix, loan_amount, annual_interest_rate, monthly_payment, util_person):
    # Find the row corresponding to the given annual interest rate
    row = utility_matrix.iloc[annual_interest_rate-1]
    annual_payment = monthly_payment*12
    payed = 0

    # Find the column where the annual payment surpasses the threshold
    for i,column in enumerate(row):
        payed += annual_payment
        if payed >= (loan_amount * column):
            print(f"Column value in utility_Bank: {column}")
            print(f"Corresponding value in utility_person: {util_person.iloc[annual_interest_rate-1, i]}")
            print(f"Years to pay off: {i+1}")
            return None

    # If the loop completes without finding a term, return None
    return print("Utenfor rekkevidden")

In [142]:
loan_amount = 2000000
annual_interest_rate = 2
montly_pay = 12000

result = find_loan_term(bankU, loan_amount, annual_interest_rate, montly_pay, personU)

Column value in utility_Bank: 1.546
Corresponding value in utility_person: 0.6468
Years to pay off: 22