In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Utility

In [27]:
personU = pd.read_csv('person_utility.csv')
bankU = pd.read_csv('bank_utility.csv')

bankU = bankU.drop('Unnamed: 0', axis=1, errors='ignore')
personU = personU.drop('Unnamed: 0', axis=1, errors='ignore')

In [28]:
personU

,1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,30
0,0.9901,0.9803,0.9706,0.9610,0.9515,0.9420,0.9327,0.9235,0.9143,0.9053,...,0.8114,0.8034,0.7954,0.7876,0.7798,0.7720,0.7644,0.7568,0.7493,0.7419
1,0.9804,0.9612,0.9423,0.9238,0.9057,0.8880,0.8706,0.8535,0.8368,0.8203,...,0.6598,0.6468,0.6342,0.6217,0.6095,0.5976,0.5859,0.5744,0.5631,0.5521
2,0.9709,0.9426,0.9151,0.8885,0.8626,0.8375,0.8131,0.7894,0.7664,0.7441,...,0.5375,0.5219,0.5067,0.4919,0.4776,0.4637,0.4502,0.4371,0.4243,0.4120
3,0.9615,0.9246,0.8890,0.8548,0.8219,0.7903,0.7599,0.7307,0.7026,0.6756,...,0.4388,0.4220,0.4057,0.3901,0.3751,0.3607,0.3468,0.3335,0.3207,0.3083
4,0.9524,0.9070,0.8638,0.8227,0.7835,0.7462,0.7107,0.6768,0.6446,0.6139,...,0.3589,0.3418,0.3256,0.3101,0.2953,0.2812,0.2678,0.2551,0.2429,0.2314
5,0.9434,0.8900,0.8396,0.7921,0.7473,0.7050,0.6651,0.6274,0.5919,0.5584,...,0.2942,0.2775,0.2618,0.2470,0.2330,0.2198,0.2074,0.1956,0.1846,0.1741
6,0.9346,0.8734,0.8163,0.7629,0.7130,0.6663,0.6227,0.5820,0.5439,0.5083,...,0.2415,0.2257,0.2109,0.1971,0.1842,0.1722,0.1609,0.1504,0.1406,0.1314
7,0.9259,0.8573,0.7938,0.7350,0.6806,0.6302,0.5835,0.5403,0.5002,0.4632,...,0.1987,0.1839,0.1703,0.1577,0.1460,0.1352,0.1252,0.1159,0.1073,0.0994
8,0.9174,0.8417,0.7722,0.7084,0.6499,0.5963,0.5470,0.5019,0.4604,0.4224,...,0.1637,0.1502,0.1378,0.1264,0.1160,0.1064,0.0976,0.0895,0.0822,0.0754
9,0.9091,0.8264,0.7513,0.6830,0.6209,0.5645,0.5132,0.4665,0.4241,0.3855,...,0.1351,0.1228,0.1117,0.1015,0.0923,0.0839,0.0763,0.0693,0.0630,0.0573

## probability

In [29]:
prob = pd.read_csv('prob.csv')
prob = prob['Probability']
prob = prob.values.reshape(-1, 1)

## Decsion matrix

In [30]:
result_matrix_person = np.matmul(personU.transpose() , prob)

In [31]:
result_matrix_person

           0
1   0.973398
2   0.947726
3   0.922915
4   0.899003
5   0.875900
6   0.853587
7   0.832025
8   0.811165
9   0.791002
10  0.771492
11  0.752640
12  0.734374
13  0.716712
14  0.699602
15  0.683007
16  0.666935
17  0.651403
18  0.636303
19  0.621649
20  0.607487
21  0.593705
22  0.580352
23  0.567405
24  0.554808
25  0.542589
26  0.530722
27  0.519208
28  0.507998
29  0.497082
30  0.486524

In [32]:
result_matrix_bank = np.matmul(bankU.transpose() , prob)

In [33]:
result_matrix_bank

           0
1   1.027589
2   1.056202
3   1.085875
4   1.116683
5   1.148686
6   1.181901
7   1.216386
8   1.252272
9   1.289526
10  1.328263
11  1.368606
12  1.410552
13  1.454231
14  1.499750
15  1.547152
16  1.596533
17  1.647985
18  1.701673
19  1.757729
20  1.816193
21  1.877281
22  1.941023
23  2.007651
24  2.077260
25  2.150088
26  2.226261
27  2.305949
28  2.389346
29  2.476712
30  2.568232